nats:
  image: nats:alpine
  pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 8
      memory: 4Gi
    limits:
      cpu: 10
      memory: 6Gi
  
  limits:
    maxConnections: 20000

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: 3Gi
      storageDirectory: /data/
      storageClassName: standard

cluster:
  enabled: true
  name: js-nats-cluster-msp-staging
  replicas: 3

  authorization:
    user: admin
    password: password
    timeout: 0.5

gateway:
  enabled: true
  name: js-nats-cluster-msp-staging

  gateways:
  - name: js-nats-cluster-mcpworker-staging
    url: nats://nats-mcpworker-staging.mcpworker-staging.svc.cluster.local:7522
  - name: js-nats-cluster-mcpworker-production
    url: nats://nats-mcpworker-production.mcpworker-production.svc.cluster.local:7522
  - name: js-nats-cluster-msp-production
    url: nats://nats-msp-production.msp-production.svc.cluster.local:7522
  - name: js-nats-cluster-msp-staging
    url: nats://nats-msp-staging.msp-staging.svc.cluster.local:7522

exporter:
  pullPolicy: IfNotPresent
  enabled: true
  portName: csho-metrics
  containerPort: 24231


auth:
  enabled: true
  systemAccount: "SYS"
  basic:
    accounts:
      SYS:
        users:
        - user: ali
          pass: ali


natsbox:
  enabled: true
  image: docker-production-cloudshop/amakke/nats/nats-box:v0.25.3
  pullPolicy: IfNotPresent
  replicas: 10
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      memory: 800Mi